title: software-architektur.tv
tagline: Software Architektur im Stream
url: https://software-architektur.tv
repository: AlexRogalskiy/software-architektur.tv

author:
  name: Eberhard Wolff
  url: http://ewolff.com
  twitter: ewolff

plugins:
  - jekyll-feed

markdown: kramdown
